### ISSUE TITLE
login_senha

### ISSUE THREAD

**Issue by luisademelo14** [luisademelo14/mc656_projeto#1]
Permite que os usuários se inscrevam e façam login na plataforma, usando nome do usuario, e-mail e uma senha forte

**Comment by IgorEBatista** [comment]
@luisademelo14 @gabijacob @RenanFlorencio @leticialopesms @IgorEBatista 
Alguém tem interesse em se responsabilizar por essa tarefa?

**Comment by gabijacob** [comment]
n tenho ideia de como faz mas pode ser eu kkkkk

**Comment by luisademelo14** [comment]
issue resolvida

**Comment by luisademelo14** [comment]
issue aberta novamente, pois falta a parte dos testes
