### ISSUE TITLE
História 2.1: Adição de conexões

### ISSUE THREAD

**Issue by leticialopesms** [luisademelo14/mc656_projeto#23]
### Descrição:
**Como:** estudante
**Eu gostaria de:** adicionar colegas à minha rede de conexões
**De forma que:** eu possa acompanhar suas atividades e manter contato

### Critérios de Aceitação
- O usuário deve conseguir encontrar outros estudantes pelo nome ou outras informações (como escola). Um botão "Adicionar Conexão" deve estar visível no perfil do estudante encontrado;
- Após adicionar a conexão, o estudante deve visualizar a nova conexão em sua lista de contatos.

**Comment by brenofranca83** [comment]
Histórias devem eviar o uso de elementos de interface com usuário como botões, menus...
