### ISSUE TITLE
História 3.1: Interação no Feed

### ISSUE THREAD

**Issue by leticialopesms** [luisademelo14/mc656_projeto#26]
### Descrição:
**Como:** estudante
**Eu gostaria de:** interagir com as atividades dos usuários no feed
**De forma que:** eu possa curtir ou reagir à experiência dos outros estudantes no site

### Critérios de Aceitação:
- O estudante deve conseguir interagir no feed. Para isso, ele poderá selecionar o projeto no qual passou a fazer parte, e o post será um entre os pré-definidos, que conterá a atividade da qual ele passou a fazer parte, seu nome e sua foto de perfil, além da data.
- A atividade deve ser exibida no feed de atividades para outros estudantes visualizarem.

**Comment by leticialopesms** [comment]
Vamos implementar postagem de imagens no feed?

**Comment by leticialopesms** [comment]
Modificar a história, de modo que o usuário não consiga postar diretamente no Feed. A ideia é que apenas determinadas ações do usuário sejam mostradas diretamente no feed (ex.: registro, inscrição em projeto). Além disso, o usuário pode curtir um post ou acessar o link do projeto presente no post.

@IgorEBatista

**Comment by brenofranca83** [comment]
Esses critério estão dando uma noção de fluxo da funcionalidade. Não é para isso que servem; devem apoiar a verificação se a função está correta e completa.
