### ISSUE TITLE
Implementação de testes automatizados

### ISSUE THREAD

**Issue by IgorEBatista** [luisademelo14/mc656_projeto#69]
Implementar casos de testes automatizados no projeto utilizando pelo menos dois dos critérios abaixo:
- Particionamento em classes de equivalência;
- Análise de Valor Limite;
- Grafo de Causa-Efeito (Tabela de Decisão)
- Pairwise

Os casos de teste devem englobar pelo menos **3 unidades** diferentes.

**Comment by leticialopesms** [comment]
Ideias

Testes de cadastro:
* Classes de Equivalência: tratar nome, email e senha.
* Valor limite: tratar datas válidas
* Tabela de decisão: definir as condições para um login bem-sucedido

Teste para barra de pesquisa:

Teste de conexão com banco de dados:

**Comment by leticialopesms** [comment]
Para a Avaliação 5, foram implementados testes nos módulos de api register.ts e projects.ts para validar seus comportamentos.

### API de Cadastro (register.ts):
Atualizado o arquivo register.test.ts com:
- Análise de Valor Limite: Teste para datas de nascimento válidas (ontem) e inválidas (hoje).
- Tabela de Decisão: Combinações de email, data e senha, verificando que o primeiro erro detectado segue a ordem: campos vazios → email → senha → data.

### API de Projetos (projects.ts):
Criado o arquivo projects.test.ts com:

- Particionamento em Classes de Equivalência: IDs válidos/invalidos, filtragem por categoria e pesquisa por nome.
- Análise de Valor Limite: Testes para os valores mínimos e máximos do parâmetro limit.
